[build]
    base = "."
    publish = "dist"
    command = "npm run build"
    functions = "./functions"
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true
[[redirects]]
  from = "/og/*"
  to = "/.netlify/builders/og"
  status = 200
  force = true
[functions]
  node_bundler = "esbuild"